test:
	emacs -Q --batch -L .. --eval "(progn\
	(load-file \"archive-rpm-tests.el\")\
	(ert-run-tests-batch-and-exit))"

test-interactive:
	emacs -Q -L .. --eval "(progn\
	(load-file \"archive-rpm-tests.el\")\
	(ert t))"
